apiVersion: v1
kind: ConfigMap

metadata:
  name: filebeat-config
  namespace: elk

data:

  filebeat.yml: |

    filebeat.inputs:

    - type: container

      paths:
      - /var/log/containers/*recommendation*.log
      - /var/log/containers/*frontend*.log

    output.elasticsearch:

      hosts:
      - elasticsearch:9200