- name: Deploy Learning Recommender on Kubernetes
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    KUBECONFIG: /var/lib/jenkins/.kube/config

  tasks:

    # =========================
    # CORE CONFIG
    # =========================
    - name: Apply ConfigMap
      shell: kubectl apply -f ../k8s/app-configmap.yaml

    - name: Apply Secret
      shell: kubectl apply -f ../k8s/app-secret.yaml

    # =========================
    # POSTGRESQL
    # =========================
    - name: Apply PostgreSQL PV
      shell: kubectl apply -f ../k8s/postgres-pv.yaml

    - name: Apply PostgreSQL PVC
      shell: kubectl apply -f ../k8s/postgres-pvc.yaml

    - name: Apply PostgreSQL Deployment
      shell: kubectl apply -f ../k8s/postgres-deployment.yaml

    - name: Apply PostgreSQL Service
      shell: kubectl apply -f ../k8s/postgres-service.yaml

    # =========================
    # MICROSERVICES
    # =========================
    - name: Apply User Deployment
      shell: kubectl apply -f ../k8s/user-deployment.yaml

    - name: Apply User Service
      shell: kubectl apply -f ../k8s/user-service.yaml

    - name: Apply Feedback Deployment
      shell: kubectl apply -f ../k8s/feedback-deployment.yaml

    - name: Apply Feedback Service
      shell: kubectl apply -f ../k8s/feedback-service.yaml

    - name: Apply Recommendation Deployment
      shell: kubectl apply -f ../k8s/recommendation-deployment.yaml

    - name: Apply Recommendation Service
      shell: kubectl apply -f ../k8s/recommendation-service.yaml

    - name: Apply Recommendation HPA
      shell: kubectl apply -f ../k8s/recommendation-hpa.yaml

    # =========================
    # GATEWAY + FRONTEND
    # =========================
    - name: Apply Gateway Deployment
      shell: kubectl apply -f ../k8s/gateway-deployment.yaml

    - name: Apply Gateway Service
      shell: kubectl apply -f ../k8s/gateway-service.yaml

    - name: Apply Frontend Deployment
      shell: kubectl apply -f ../k8s/frontend-deployment.yaml

    - name: Apply Frontend Service
      shell: kubectl apply -f ../k8s/frontend-service.yaml

    # =========================
    # PROMETHEUS
    # =========================
    - name: Apply Prometheus Config
      shell: kubectl apply -f ../k8s/prometheus-configmap.yaml

    - name: Apply Prometheus Deployment
      shell: kubectl apply -f ../k8s/prometheus-deployment.yaml

    - name: Apply Prometheus Service
      shell: kubectl apply -f ../k8s/prometheus-service.yaml

    # --- ELK Stack Deployment ---
    
    # - name: Apply ELK Namespace
    #   shell: kubectl apply -f ../elk/elk-namespace.yaml --validate=false

    # - name: Apply Elasticsearch
    #   shell: kubectl apply -f ../elk/elasticsearch/elasticsearch-deployment.yaml --validate=false

    # - name: Apply Kibana
    #   shell: kubectl apply -f ../elk/kibana/kibana-deployment.yaml --validate=false

    # - name: Apply Filebeat Config
    #   shell: | 
    #     kubectl apply -f ../elk/namespace.yaml --validate=false
    #     kubectl apply -f ../elk/filebeat-configmap.yaml --validate=false
    #     kubectl apply -f ../elk/filebeat-k8s.yaml --validate=false
    #     kubectl apply -f ../elk/filebeat-rbac.yaml --validate=false
    #     kubectl apply -f ../elk/logstash/logstash-configmap.yaml --validate=false
    #     kubectl apply -f ../elk/logstash/logstash-deployment.yaml --validate=false