- name: Deploy Learning Recommender on Kubernetes
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    KUBECONFIG: /var/lib/jenkins/.kube/config

  tasks:

    - name: Apply ConfigMap
      shell: kubectl apply -f ../k8s/app-configmap.yaml --validate=false

    - name: Apply Secret
      shell: kubectl apply -f ../k8s/app-secret.yaml --validate=false

    - name: Apply PostgreSQL PV
      shell: kubectl apply -f ../k8s/postgres-pv.yaml --validate=false

    - name: Apply PostgreSQL PVC
      shell: kubectl apply -f ../k8s/postgres-pvc.yaml --validate=false

    - name: Apply PostgreSQL Deployment
      shell: kubectl apply -f ../k8s/postgres-deployment.yaml --validate=false

    - name: Apply PostgreSQL Service
      shell: kubectl apply -f ../k8s/postgres-service.yaml --validate=false

    - name: Apply User Service
      shell: kubectl apply -f ../k8s/user-deployment.yaml --validate=false

    - name: Apply User Service YAML
      shell: kubectl apply -f ../k8s/user-service.yaml --validate=false

    - name: Apply Feedback Service
      shell: kubectl apply -f ../k8s/feedback-deployment.yaml --validate=false

    - name: Apply Feedback Service YAML
      shell: kubectl apply -f ../k8s/feedback-service.yaml --validate=false

    - name: Apply Recommendation Service
      shell: kubectl apply -f ../k8s/recommendation-deployment.yaml --validate=false

    - name: Apply Recommendation Service YAML
      shell: kubectl apply -f ../k8s/recommendation-service.yaml --validate=false

    - name: Apply Gateway Deployment
      shell: kubectl apply -f ../k8s/gateway-deployment.yaml --validate=false

    - name: Apply Gateway Service
      shell: kubectl apply -f ../k8s/gateway-service.yaml --validate=false

    - name: Apply Frontend Deployment
      shell: kubectl apply -f ../k8s/frontend-deployment.yaml --validate=false

    - name: Apply Frontend Service
      shell: kubectl apply -f ../k8s/frontend-service.yaml --validate=false

    - name: Apply Prometheus Config
      shell: kubectl apply -f ../k8s/prometheus-configmap.yaml --validate=false

    - name: Apply Prometheus Deployment
      shell: kubectl apply -f ../k8s/prometheus-deployment.yaml --validate=false

    - name: Apply Prometheus Service
      shell: kubectl apply -f ../k8s/prometheus-service.yaml --validate=false
