- name: Deploy Learning Recommender on Kubernetes
  hosts: localhost
  tasks:

    - name: Apply postgres
      command: kubectl apply -f k8s/postgres.yaml

    - name: Apply user service
      command: kubectl apply -f k8s/user-service.yaml

    - name: Apply feedback service
      command: kubectl apply -f k8s/feedback-service.yaml

    - name: Apply recommendation service
      command: kubectl apply -f k8s/recommendation-service.yaml

    - name: Apply gateway
      command: kubectl apply -f k8s/api-gateway.yaml

    - name: Apply frontend
      command: kubectl apply -f k8s/frontend.yaml

    - name: Apply prometheus
      command: kubectl apply -f k8s/prometheus.yaml
